---
galaxy_info:
  role_name: bind_configure
  author: Companies House
  description: configure bind nameserver
  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - bind
    - dns
    - named

dependencies:
  - role: bind_install
