---
galaxy_info:
  role_name: bind_install
  author: Companies House
  description: install bind software package
  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - bind
    - dns
    - named

dependencies: []
