---
- name: Process PTR records
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/ptr_record.yml"
  loop: >-
    {{
      bind_service_records
      | selectattr('type', 'equalto', 'A')
      | list
    }}
  loop_control:
    label: "{{ item.value }}"
