---
- name: Set zone definition
  ansible.builtin.set_fact:
    bind_service_zone_definition: >-
      {{
        bind_service_zone_definitions.zones
        | selectattr('zone', 'equalto', zone_item.zone)
        | first
      }}

- name: Read current serial
  ansible.builtin.shell: >
    awk 'tolower($0) ~ /serial/ {print $1; exit}'
    {{ bind_service_zone_dir }}/{{ bind_service_zone_definition.file }}.work
  register: current_serial
  changed_when: false

- name: Validate serial format
  ansible.builtin.assert:
    that:
      - current_serial.stdout is match('^[0-9]{10}$')
    fail_msg: >-
      Invalid serial format in
      {{ bind_service_zone_definition.file }}:
      {{ current_serial.stdout }}

- name: Calculate next serial
  ansible.builtin.set_fact:
    next_serial: >-
      {{
        (
          current_serial.stdout[:8] == lookup('pipe', 'date +%Y%m%d')
        )
        | ternary(
            (current_serial.stdout | int) + 1,
            (lookup('pipe', 'date +%Y%m%d') ~ '01') | int
          )
      }}

- name: Update zone serial
  ansible.builtin.replace:
    path: "{{ bind_service_zone_dir }}/{{ bind_service_zone_definition.file }}.work"
    regexp: '^(\s*)\d+\s*;\s*[Ss]erial.*$'
    replace: '{{ next_serial }} ; serial'
