---
- name: Validate affected zones
  ansible.builtin.include_tasks: validate_zone.yml
  loop: "{{ bind_service_records | unique(attribute='zone') }}"
  loop_control:
    loop_var: zone_item
    label: "{{ zone_item.zone }}"
